WIP: Test linux build patch

diff --git a/.github/workflows/build-test-package.yml b/.github/workflows/build-test-package.yml
--- a/.github/workflows/build-test-package.yml
+++ b/.github/workflows/build-test-package.yml
@@ -57,10 +57,63 @@ jobs:
     - name: 'Build 🐍 Python 📦 package'
       run: |
         export ITK_PACKAGE_VERSION=${{ env.itk-wheel-tag }}
+
+        # FIXME get linux build script Patch
+        mkdir patch
+        pushd patch
+          git clone https://github.com/tbirdso/ITKPythonPackage.git
+          cd ITKPythonPackage
+          git checkout "1f663d45384fc9eb2188cf1ed5f34f1bbea097ef"
+          cat scripts/internal/manylinux-build-module-wheels.sh
+        popd
+
         for tarball in "-manylinux_2_28" "-manylinux2014"; do
+          echo "tarball ${tarball}"
           rm -rf ITKPythonPackage
           export TARBALL_SPECIALIZATION=${tarball}
-          ./dockcross-manylinux-download-cache-and-build-module-wheels.sh cp${{ matrix.python-version }}
+          export PYTHON_CP=cp${{ matrix.python-version }}
+
+          # From ITKPythonPackage
+          # Packages distributed by github are in zstd format, so we need to download that binary to uncompress
+          if [[ ! -f zstd-1.2.0-linux.tar.gz ]]; then
+            curl https://data.kitware.com/api/v1/file/592dd8068d777f16d01e1a92/download -o zstd-1.2.0-linux.tar.gz
+            gunzip -d zstd-1.2.0-linux.tar.gz
+            tar xf zstd-1.2.0-linux.tar
+          fi
+          if [[ ! -f ./zstd-1.2.0-linux/bin/unzstd ]]; then
+            echo "ERROR: can not find required binary './zstd-1.2.0-linux/bin/unzstd'"
+            exit 255
+          fi
+
+          TARBALL_NAME="ITKPythonBuilds-linux${TARBALL_SPECIALIZATION}.tar"
+
+          if [[ ! -f ${TARBALL_NAME}.zst ]]; then
+            curl -L https://github.com/InsightSoftwareConsortium/ITKPythonBuilds/releases/download/${ITK_PACKAGE_VERSION:=v5.2.0.post1}/${TARBALL_NAME}.zst -O
+          fi
+          if [[ ! -f ./${TARBALL_NAME}.zst ]]; then
+            echo "ERROR: can not find required binary './${TARBALL_NAME}.zst'"
+            exit 255
+          fi
+          ./zstd-1.2.0-linux/bin/unzstd ./${TARBALL_NAME}.zst -o ${TARBALL_NAME}
+          echo "Extracting files relevant for: $PYTHON_CP";
+          tar xf ${TARBALL_NAME} ITKPythonPackage/scripts/
+          tar xf ${TARBALL_NAME} ITKPythonPackage/ITK-source/
+          tar xf ${TARBALL_NAME} ITKPythonPackage/oneTBB-prefix/
+          tar xf ${TARBALL_NAME} --wildcards ITKPythonPackage/ITK-$PYTHON_CP*
+          rm ${TARBALL_NAME}
+          if [[ ! -f ./ITKPythonPackage/scripts/dockcross-manylinux-build-module-wheels.sh ]]; then
+            echo "ERROR: can not find required binary './ITKPythonPackage/scripts/dockcross-manylinux-build-module-wheels.sh'"
+            exit 255
+          fi
+          cp -a ITKPythonPackage/oneTBB-prefix ./
+
+          #FIXME patch linux build script
+          cp patch/ITKPythonPackage/scripts/internal/manylinux-build-module-wheels.sh ITKPythonPackage/scripts/internal/manylinux-build-module-wheels.sh
+          echo "Patched Linux build script at"
+          pwd
+          cat ITKPythonPackage/scripts/internal/manylinux-build-module-wheels.sh
+
+          ./ITKPythonPackage/scripts/dockcross-manylinux-build-module-wheels.sh "$@"
         done
 
     - name: Publish Python package as GitHub Artifact
